behaviors:
  BattleGameBehaviour:
    trainer_type: ppo
    max_steps: 1.0e7
    time_horizon: 128        
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
    network_settings:
      hidden_units: 400
      num_layers: 2
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
    self_play:
      window: 5
      play_against_current_self_ratio: 0.5
      save_steps: 50000